server.port=8080
# Database
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5433/tabletennis
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}
# Security for dev environment
jwt.SECRET_KEY=${DEV_JWT_SECRET}
spring.jpa.show-sql=true